package Netspan.NBI_15_5.Software;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-02-06T16:26:43.982+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://Airspan.Netspan.WebServices", name = "SoftwareSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SoftwareSoap {

    /**
     * Clone a Software Server. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerClone", action = "http://Airspan.Netspan.WebServices/SoftwareServerClone")
    @RequestWrapper(localName = "SoftwareServerClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerClone")
    @ResponseWrapper(localName = "SoftwareServerCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerCloneResponse")
    @WebResult(name = "SoftwareServerCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwServerResponse softwareServerClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "SoftwareServer", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwServerWs softwareServer,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a Software Server. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerCreate", action = "http://Airspan.Netspan.WebServices/SoftwareServerCreate")
    @RequestWrapper(localName = "SoftwareServerCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerCreate")
    @ResponseWrapper(localName = "SoftwareServerCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerCreateResponse")
    @WebResult(name = "SoftwareServerCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwServerResponse softwareServerCreate(
        @WebParam(name = "SoftwareServer", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwServerWs softwareServer,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a Software Image. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageGet", action = "http://Airspan.Netspan.WebServices/SoftwareImageGet")
    @RequestWrapper(localName = "SoftwareImageGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageGet")
    @ResponseWrapper(localName = "SoftwareImageGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageGetResponse")
    @WebResult(name = "SoftwareImageGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwImageResponse softwareImageGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the Software configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareConfigSet", action = "http://Airspan.Netspan.WebServices/SoftwareConfigSet")
    @RequestWrapper(localName = "SoftwareConfigSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareConfigSet")
    @ResponseWrapper(localName = "SoftwareConfigSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareConfigSetResponse")
    @WebResult(name = "SoftwareConfigSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.NodeActionResult softwareConfigSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "SoftwareDetails", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwConfigSetWs softwareDetails,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more Software Images. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageDelete", action = "http://Airspan.Netspan.WebServices/SoftwareImageDelete")
    @RequestWrapper(localName = "SoftwareImageDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageDelete")
    @ResponseWrapper(localName = "SoftwareImageDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageDeleteResponse")
    @WebResult(name = "SoftwareImageDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwImageResponse softwareImageDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a Software Server. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerGet", action = "http://Airspan.Netspan.WebServices/SoftwareServerGet")
    @RequestWrapper(localName = "SoftwareServerGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerGet")
    @ResponseWrapper(localName = "SoftwareServerGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerGetResponse")
    @WebResult(name = "SoftwareServerGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwServerResponse softwareServerGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a Software Server. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerUpdate", action = "http://Airspan.Netspan.WebServices/SoftwareServerUpdate")
    @RequestWrapper(localName = "SoftwareServerUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerUpdate")
    @ResponseWrapper(localName = "SoftwareServerUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerUpdateResponse")
    @WebResult(name = "SoftwareServerUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwServerResponse softwareServerUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "SoftwareServer", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwServerWs softwareServer,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a Software Image. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageClone", action = "http://Airspan.Netspan.WebServices/SoftwareImageClone")
    @RequestWrapper(localName = "SoftwareImageClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageClone")
    @ResponseWrapper(localName = "SoftwareImageCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageCloneResponse")
    @WebResult(name = "SoftwareImageCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwImageResponse softwareImageClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "SoftwareImage", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwImageWs softwareImage,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of Software Servers. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerList", action = "http://Airspan.Netspan.WebServices/SoftwareServerList")
    @RequestWrapper(localName = "SoftwareServerList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerList")
    @ResponseWrapper(localName = "SoftwareServerListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerListResponse")
    @WebResult(name = "SoftwareServerListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.NameResult softwareServerList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a Software Image. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageUpdate", action = "http://Airspan.Netspan.WebServices/SoftwareImageUpdate")
    @RequestWrapper(localName = "SoftwareImageUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageUpdate")
    @ResponseWrapper(localName = "SoftwareImageUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageUpdateResponse")
    @WebResult(name = "SoftwareImageUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwImageResponse softwareImageUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "SoftwareImage", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwImageWs softwareImage,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more Software Servers. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareServerDelete", action = "http://Airspan.Netspan.WebServices/SoftwareServerDelete")
    @RequestWrapper(localName = "SoftwareServerDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerDelete")
    @ResponseWrapper(localName = "SoftwareServerDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareServerDeleteResponse")
    @WebResult(name = "SoftwareServerDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwServerResponse softwareServerDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of Software Images. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageList", action = "http://Airspan.Netspan.WebServices/SoftwareImageList")
    @RequestWrapper(localName = "SoftwareImageList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageList")
    @ResponseWrapper(localName = "SoftwareImageListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageListResponse")
    @WebResult(name = "SoftwareImageListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.NameResult softwareImageList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a Software Image. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareImageCreate", action = "http://Airspan.Netspan.WebServices/SoftwareImageCreate")
    @RequestWrapper(localName = "SoftwareImageCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageCreate")
    @ResponseWrapper(localName = "SoftwareImageCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareImageCreateResponse")
    @WebResult(name = "SoftwareImageCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SwImageResponse softwareImageCreate(
        @WebParam(name = "SoftwareImage", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_15_5.Software.SwImageWs softwareImage,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Software status of the specified nodes. If no nodes specified, returns the Software status of all nodes in the network. Requires NBIF Extensions Licence.
     */
    @WebMethod(operationName = "SoftwareStatusGet", action = "http://Airspan.Netspan.WebServices/SoftwareStatusGet")
    @RequestWrapper(localName = "SoftwareStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareStatusGet")
    @ResponseWrapper(localName = "SoftwareStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_15_5.Software.SoftwareStatusGetResponse")
    @WebResult(name = "SoftwareStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    public Netspan.NBI_15_5.Software.SoftwareStatusGetWs softwareStatusGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );
}
