
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package Netspan.NBI_14_0.API.FaultManagement;

import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-05T12:19:12.012+03:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "FaultManagement",
                      portName = "FaultManagementSoap",
                      targetNamespace = "http://Airspan.Netspan.WebServices",
                      wsdlLocation = "http://asil-svg-nms6/ws/14.0/FaultManagement.asmx?WSDL",
                      endpointInterface = "Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap")
                      
public class FaultManagementSoapImpl implements FaultManagementSoap {

    private static final Logger LOG = Logger.getLogger(FaultManagementSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmRelease(java.util.List<java.math.BigInteger>  alarmID ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult alarmRelease(java.util.List<java.math.BigInteger> alarmID,Credentials credentials) { 
        LOG.info("Executing operation alarmRelease");
        System.out.println(alarmID);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmDelete(java.util.List<java.math.BigInteger>  alarmID ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult alarmDelete(java.util.List<java.math.BigInteger> alarmID,Credentials credentials) { 
        LOG.info("Executing operation alarmDelete");
        System.out.println(alarmID);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmUnacknowledge(java.util.List<java.math.BigInteger>  alarmID ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult alarmUnacknowledge(java.util.List<java.math.BigInteger> alarmID,Credentials credentials) { 
        LOG.info("Executing operation alarmUnacknowledge");
        System.out.println(alarmID);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmAcknowledge(java.util.List<java.math.BigInteger>  alarmID ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult alarmAcknowledge(java.util.List<java.math.BigInteger> alarmID,Credentials credentials) { 
        LOG.info("Executing operation alarmAcknowledge");
        System.out.println(alarmID);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmList(Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmResultList alarmList(Credentials credentials) { 
        LOG.info("Executing operation alarmList");
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmResultList _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmListNode(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmResultList alarmListNode(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation alarmListNode");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmResultList _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.FaultManagement.FaultManagementSoap#alarmListChanged(javax.xml.datatype.XMLGregorianCalendar  startDate ,)Netspan.NBI_14_0.API.FaultManagement.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.FaultManagement.AlarmResultList alarmListChanged(javax.xml.datatype.XMLGregorianCalendar startDate,Credentials credentials) { 
        LOG.info("Executing operation alarmListChanged");
        System.out.println(startDate);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.FaultManagement.AlarmResultList _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
