package Netspan.NBI_15_5.FaultManagement;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2017-02-06T16:24:13.446+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebServiceClient(name = "FaultManagement", 
                  wsdlLocation = "http://192.168.58.46/ws/15.5/FaultManagement.asmx?WSDL",
                  targetNamespace = "http://Airspan.Netspan.WebServices") 
public class FaultManagement extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Airspan.Netspan.WebServices", "FaultManagement");
    public final static QName FaultManagementSoap = new QName("http://Airspan.Netspan.WebServices", "FaultManagementSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.58.46/ws/15.5/FaultManagement.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FaultManagement.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.58.46/ws/15.5/FaultManagement.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public FaultManagement(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FaultManagement(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FaultManagement() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultManagement(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultManagement(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FaultManagement(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns FaultManagementSoap
     */
    @WebEndpoint(name = "FaultManagementSoap")
    public FaultManagementSoap getFaultManagementSoap() {
        return super.getPort(FaultManagementSoap, FaultManagementSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FaultManagementSoap
     */
    @WebEndpoint(name = "FaultManagementSoap")
    public FaultManagementSoap getFaultManagementSoap(WebServiceFeature... features) {
        return super.getPort(FaultManagementSoap, FaultManagementSoap.class, features);
    }

}
