
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package Netspan.NBI_15_1.Backhaul;
import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-12-06T19:16:58.988+02:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Backhaul",
                      portName = "BackhaulSoap",
                      targetNamespace = "http://Airspan.Netspan.WebServices",
                      wsdlLocation = "http://192.168.58.103//ws/15.0/Backhaul.asmx?WSDL",
                      endpointInterface = "Netspan.NBI_15_1.Backhaul.BackhaulSoap")
                      
public class BackhaulSoapImpl implements BackhaulSoap {

    private static final Logger LOG = Logger.getLogger(BackhaulSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigDelete(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayPnpConfigDelete(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigDelete");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileCreate(Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseRadioProfileCreate(Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileCreate");
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseStateSet(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.IbBaseStates  iBridgeBaseRfState ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBaseStateSet(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.IbBaseStates iBridgeBaseRfState,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseStateSet");
        System.out.println(nodeName);
        System.out.println(iBridgeBaseRfState);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigClone(java.lang.String  existingNodeName ,)Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.RelayDetailsPnp  relayDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayPnpConfigClone(java.lang.String existingNodeName,Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.RelayDetailsPnp relayDetail,Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigClone");
        System.out.println(existingNodeName);
        System.out.println(pnpDetail);
        System.out.println(relayDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileClone(java.lang.String  cloneFromName ,)Netspan.NBI_15_1.Backhaul.IbTermRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeTermRadioProfileClone(java.lang.String cloneFromName,Netspan.NBI_15_1.Backhaul.IbTermRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileClone");
        System.out.println(cloneFromName);
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileCreate(Netspan.NBI_15_1.Backhaul.RelayProfile  relayProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse relayProfileCreate(Netspan.NBI_15_1.Backhaul.RelayProfile relayProfile,Credentials credentials) { 
        LOG.info("Executing operation relayProfileCreate");
        System.out.println(relayProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileDelete(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeTermRadioProfileDelete(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileDelete");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbBaseRadioProfileGetResult iBridgeBaseRadioProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbBaseRadioProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseSystemDefaultProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IBridgeBaseSystemDefaultProfileGetResult iBridgeBaseSystemDefaultProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseSystemDefaultProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IBridgeBaseSystemDefaultProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult iBridgeTermRadioProfileList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseStateGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbBaseStateGetResult iBridgeBaseStateGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseStateGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbBaseStateGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileUpdate(java.lang.String  name ,)Netspan.NBI_15_1.Backhaul.RelayProfile  relayProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse relayProfileUpdate(java.lang.String name,Netspan.NBI_15_1.Backhaul.RelayProfile relayProfile,Credentials credentials) { 
        LOG.info("Executing operation relayProfileUpdate");
        System.out.println(name);
        System.out.println(relayProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbBaseManagementProfileGetResult iBridgeBaseManagementProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbBaseManagementProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileClone(java.lang.String  cloneFromName ,)Netspan.NBI_15_1.Backhaul.RelayProfile  relayProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse relayProfileClone(java.lang.String cloneFromName,Netspan.NBI_15_1.Backhaul.RelayProfile relayProfile,Credentials credentials) { 
        LOG.info("Executing operation relayProfileClone");
        System.out.println(cloneFromName);
        System.out.println(relayProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relaySystemDefaultProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.RelaySystemDefaultProfileGetResult relaySystemDefaultProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation relaySystemDefaultProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.RelaySystemDefaultProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigUpdate(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp  iBridgeBaseDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBasePnpConfigUpdate(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp iBridgeBaseDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigUpdate");
        System.out.println(nodeName);
        System.out.println(pnpDetail);
        System.out.println(iBridgeBaseDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigCreate(Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp  iBridgeTermDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeTermPnpConfigCreate(Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp iBridgeTermDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigCreate");
        System.out.println(pnpDetail);
        System.out.println(iBridgeTermDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigClone(java.lang.String  existingNodeName ,)Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp  iBridgeBaseDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBasePnpConfigClone(java.lang.String existingNodeName,Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp iBridgeBaseDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigClone");
        System.out.println(existingNodeName);
        System.out.println(pnpDetail);
        System.out.println(iBridgeBaseDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigGet(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.RelayPnpConfigGetResult relayPnpConfigGet(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigGet");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.RelayPnpConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileDelete(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseManagementProfileDelete(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileDelete");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileUpdate(java.lang.String  name ,)Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile  managementProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseManagementProfileUpdate(java.lang.String name,Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile managementProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileUpdate");
        System.out.println(name);
        System.out.println(managementProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileClone(java.lang.String  cloneFromName ,)Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile  managementProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseManagementProfileClone(java.lang.String cloneFromName,Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile managementProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileClone");
        System.out.println(cloneFromName);
        System.out.println(managementProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult relayProfileList(Credentials credentials) { 
        LOG.info("Executing operation relayProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeListResult iBridgeBasePnpConfigList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermSystemDefaultProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult iBridgeTermSystemDefaultProfileList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermSystemDefaultProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IBridgeTermPnpConfigGetResult iBridgeTermPnpConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IBridgeTermPnpConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayConfigSet(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.RelayDetails  relayDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayConfigSet(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.RelayDetails relayDetail,Credentials credentials) { 
        LOG.info("Executing operation relayConfigSet");
        System.out.println(nodeName);
        System.out.println(relayDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult iBridgeBaseRadioProfileList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileDelete(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseRadioProfileDelete(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileDelete");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbTermRadioProfileGetResult iBridgeTermRadioProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbTermRadioProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.RelayConfigGetResult relayConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation relayConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.RelayConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relaySystemDefaultProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult relaySystemDefaultProfileList(Credentials credentials) { 
        LOG.info("Executing operation relaySystemDefaultProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseSystemDefaultProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult iBridgeBaseSystemDefaultProfileList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseSystemDefaultProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeListResult iBridgeTermPnpConfigList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileClone(java.lang.String  cloneFromName ,)Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseRadioProfileClone(java.lang.String cloneFromName,Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileClone");
        System.out.println(cloneFromName);
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseRadioProfileUpdate(java.lang.String  name ,)Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseRadioProfileUpdate(java.lang.String name,Netspan.NBI_15_1.Backhaul.IBridgeBaseRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRadioProfileUpdate");
        System.out.println(name);
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NameResult iBridgeBaseManagementProfileList(Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigClone(java.lang.String  existingNodeName ,)Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp  iBridgeTermDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeTermPnpConfigClone(java.lang.String existingNodeName,Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp iBridgeTermDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigClone");
        System.out.println(existingNodeName);
        System.out.println(pnpDetail);
        System.out.println(iBridgeTermDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IBridgeBasePnpConfigGetResult iBridgeBasePnpConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IBridgeBasePnpConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigUpdate(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.RelayDetailsPnp  relayDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayPnpConfigUpdate(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.RelayDetailsPnp relayDetail,Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigUpdate");
        System.out.println(nodeName);
        System.out.println(pnpDetail);
        System.out.println(relayDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbTermConfigGetResult iBridgeTermConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbTermConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayRedirect(Netspan.NBI_15_1.Backhaul.RelayRedirectDetailWs  relayRedirectDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayRedirect(Netspan.NBI_15_1.Backhaul.RelayRedirectDetailWs relayRedirectDetail,Credentials credentials) { 
        LOG.info("Executing operation relayRedirect");
        System.out.println(relayRedirectDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigCreate(Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.RelayDetailsPnp  relayDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayPnpConfigCreate(Netspan.NBI_15_1.Backhaul.RelayPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.RelayDetailsPnp relayDetail,Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigCreate");
        System.out.println(pnpDetail);
        System.out.println(relayDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileUpdate(java.lang.String  name ,)Netspan.NBI_15_1.Backhaul.IbTermRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeTermRadioProfileUpdate(java.lang.String name,Netspan.NBI_15_1.Backhaul.IbTermRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileUpdate");
        System.out.println(name);
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigDelete(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBasePnpConfigDelete(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigDelete");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#ib440ConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.Ib440ConfigGetResult ib440ConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation ib440ConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.Ib440ConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileDelete(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse relayProfileDelete(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation relayProfileDelete");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.RelayProfileGetResult relayProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation relayProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.RelayProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermSystemDefaultProfileGet(java.util.List<java.lang.String>  name ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IBridgeTermSystemDefaultProfileGetResult iBridgeTermSystemDefaultProfileGet(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermSystemDefaultProfileGet");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IBridgeTermSystemDefaultProfileGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayPnpConfigList(Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeListResult relayPnpConfigList(Credentials credentials) { 
        LOG.info("Executing operation relayPnpConfigList");
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseConfigGet(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.IbBaseConfigGetResult iBridgeBaseConfigGet(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseConfigGet");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.IbBaseConfigGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBasePnpConfigCreate(Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp  iBridgeBaseDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBasePnpConfigCreate(Netspan.NBI_15_1.Backhaul.IBridgeBasePnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IbBaseDetailsPnp iBridgeBaseDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBasePnpConfigCreate");
        System.out.println(pnpDetail);
        System.out.println(iBridgeBaseDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseConfigSet(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.IbBaseDetails  iBridgeBaseDetails ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeBaseConfigSet(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.IbBaseDetails iBridgeBaseDetails,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseConfigSet");
        System.out.println(nodeName);
        System.out.println(iBridgeBaseDetails);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermRadioProfileCreate(Netspan.NBI_15_1.Backhaul.IbTermRadioProfile  radioProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeTermRadioProfileCreate(Netspan.NBI_15_1.Backhaul.IbTermRadioProfile radioProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRadioProfileCreate");
        System.out.println(radioProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#ib440ConfigSet(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.Ib440DetailsSetWs  ib440Details ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult ib440ConfigSet(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.Ib440DetailsSetWs ib440Details,Credentials credentials) { 
        LOG.info("Executing operation ib440ConfigSet");
        System.out.println(nodeName);
        System.out.println(ib440Details);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigDelete(java.util.List<java.lang.String>  nodeName ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeTermPnpConfigDelete(java.util.List<java.lang.String> nodeName,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigDelete");
        System.out.println(nodeName);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermPnpConfigUpdate(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs  pnpDetail ,)Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp  iBridgeTermDetail ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeTermPnpConfigUpdate(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.IBridgeTermPnpDetailWs pnpDetail,Netspan.NBI_15_1.Backhaul.IBridgeTermDetailsPnp iBridgeTermDetail,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermPnpConfigUpdate");
        System.out.println(nodeName);
        System.out.println(pnpDetail);
        System.out.println(iBridgeTermDetail);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#relayForceScan(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult relayForceScan(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation relayForceScan");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeTermConfigSet(java.lang.String  nodeName ,)Netspan.NBI_15_1.Backhaul.IBridgeTermDetails  iBridgeTermDetails ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.NodeActionResult iBridgeTermConfigSet(java.lang.String nodeName,Netspan.NBI_15_1.Backhaul.IBridgeTermDetails iBridgeTermDetails,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermConfigSet");
        System.out.println(nodeName);
        System.out.println(iBridgeTermDetails);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Backhaul.BackhaulSoap#iBridgeBaseManagementProfileCreate(Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile  managementProfile ,)Netspan.NBI_15_1.Backhaul.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Backhaul.ProfileResponse iBridgeBaseManagementProfileCreate(Netspan.NBI_15_1.Backhaul.IBridgeBaseManagementProfile managementProfile,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseManagementProfileCreate");
        System.out.println(managementProfile);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Backhaul.ProfileResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
