
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package Netspan.NBI_14_0.API.Inventory;

import java.util.logging.Logger;


/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-05T12:19:08.754+03:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Inventory",
                      portName = "InventorySoap",
                      targetNamespace = "http://Airspan.Netspan.WebServices",
                      wsdlLocation = "http://asil-svg-nms6/ws/14.0/Inventory.asmx?WSDL",
                      endpointInterface = "Netspan.NBI_14_0.API.Inventory.InventorySoap")
                      
public class InventorySoapImpl implements InventorySoap {

    private static final Logger LOG = Logger.getLogger(InventorySoapImpl.class.getName());

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#discoveryTaskList(Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NameResult discoveryTaskList(Credentials credentials) { 
        LOG.info("Executing operation discoveryTaskList");
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NameResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeReset(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeActionResult nodeReset(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation nodeReset");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeDelete(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeActionResult nodeDelete(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation nodeDelete");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#discoveryTaskDelete(java.util.List<java.lang.String>  name ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.DiscoveryTaskActionResult discoveryTaskDelete(java.util.List<java.lang.String> name,Credentials credentials) { 
        LOG.info("Executing operation discoveryTaskDelete");
        System.out.println(name);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.DiscoveryTaskActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeRename(java.lang.String  nodeNameOld ,)java.lang.String  nodeNameNew ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.WsResponse nodeRename(java.lang.String nodeNameOld,java.lang.String nodeNameNew,Credentials credentials) { 
        LOG.info("Executing operation nodeRename");
        System.out.println(nodeNameOld);
        System.out.println(nodeNameNew);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.WsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeResetForced(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeActionResult nodeResetForced(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation nodeResetForced");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeInfoGet(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeDetailGetResult nodeInfoGet(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation nodeInfoGet");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeDetailGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#discoveryTaskAddSnmpV2(java.lang.String  name ,)java.lang.String  ipAddress ,)java.lang.Integer  port ,)java.lang.String  readCommunity ,)java.lang.String  writeCommunity ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.WsResponse discoveryTaskAddSnmpV2(java.lang.String name,java.lang.String ipAddress,java.lang.Integer port,java.lang.String readCommunity,java.lang.String writeCommunity,Credentials credentials) { 
        LOG.info("Executing operation discoveryTaskAddSnmpV2");
        System.out.println(name);
        System.out.println(ipAddress);
        System.out.println(port);
        System.out.println(readCommunity);
        System.out.println(writeCommunity);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.WsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#discoveryTaskAddSnmpV3(java.lang.String  name ,)java.lang.String  ipAddress ,)java.lang.Integer  port ,)Netspan.NBI_14_0.API.Inventory.Snmpv3UserNames  snmpUsername ,)java.lang.String  snmpPassword ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.WsResponse discoveryTaskAddSnmpV3(java.lang.String name,java.lang.String ipAddress,java.lang.Integer port,Netspan.NBI_14_0.API.Inventory.Snmpv3UserNames snmpUsername,java.lang.String snmpPassword,Credentials credentials) { 
        LOG.info("Executing operation discoveryTaskAddSnmpV3");
        System.out.println(name);
        System.out.println(ipAddress);
        System.out.println(port);
        System.out.println(snmpUsername);
        System.out.println(snmpPassword);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.WsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeList(Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeListResult nodeList(Credentials credentials) { 
        LOG.info("Executing operation nodeList");
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_0.API.Inventory.InventorySoap#nodeReprovision(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_14_0.API.Inventory.Credentials  credentials )*
     */
    public Netspan.NBI_14_0.API.Inventory.NodeActionResult nodeReprovision(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation nodeReprovision");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_0.API.Inventory.NodeActionResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
