package Netspan.NBI_17_0.Lte;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-02-28T15:40:11.355+02:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "Lte",
                  wsdlLocation = "http://192.168.58.103/ws/17.0/Lte.asmx?WSDL",
                  targetNamespace = "http://Airspan.Netspan.WebServices")
public class Lte extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Airspan.Netspan.WebServices", "Lte");
    public final static QName LteSoap = new QName("http://Airspan.Netspan.WebServices", "LteSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.58.103/ws/17.0/Lte.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Lte.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.58.103/ws/17.0/Lte.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Lte(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Lte(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Lte() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Lte(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Lte(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Lte(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns LteSoap
     */
    @WebEndpoint(name = "LteSoap")
    public LteSoap getLteSoap() {
        return super.getPort(LteSoap, LteSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LteSoap
     */
    @WebEndpoint(name = "LteSoap")
    public LteSoap getLteSoap(WebServiceFeature... features) {
        return super.getPort(LteSoap, LteSoap.class, features);
    }

}
