
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package Netspan.NBI_14_50.API.Status;

import java.util.logging.Logger;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-02T16:24:47.144+02:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Status",
                      portName = "StatusSoap",
                      targetNamespace = "http://Airspan.Netspan.WebServices",
                      wsdlLocation = "http://asil-svg-nms8/ws/14.5/Status.asmx?WSDL",
                      endpointInterface = "Netspan.NBI_14_50.API.Status.StatusSoap")
                      
public class StatusSoapImpl implements StatusSoap {

    private static final Logger LOG = Logger.getLogger(StatusSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeGpsGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeGpsGetResult nodeGpsGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeGpsGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeGpsGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbBackhaulInterfaceStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteBackhaulIfGetResult enbBackhaulInterfaceStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbBackhaulInterfaceStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteBackhaulIfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeSoftwareStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeSoftwareGetResult nodeSoftwareStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeSoftwareStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeSoftwareGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeTemperatureGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeSensorGetResult nodeTemperatureGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeTemperatureGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbSonPciStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteSonPciGetResult enbSonPciStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonPciStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteSonPciGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbEmbmsStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeEmbmsGetResult enbEmbmsStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbEmbmsStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeEmbmsGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeVoltageGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeSensorGetResult nodeVoltageGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeVoltageGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#iBridgeBaseRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.IBridgeBaseRfGetResult iBridgeBaseRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.IBridgeBaseRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbIpThroughputStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteIpThroughputGetResult enbIpThroughputStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbIpThroughputStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteIpThroughputGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbConnectedUeStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteUeGetResult enbConnectedUeStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbConnectedUeStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteUeGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbWifiStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteWifiGetResult enbWifiStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbWifiStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteWifiGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbSonAnrStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteSonAnrGetResult enbSonAnrStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonAnrStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteSonAnrGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#ib440InterfaceStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.Ib440InterfaceGetResult ib440InterfaceStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440InterfaceStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.Ib440InterfaceGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbSonRachStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteSonRachGetResult enbSonRachStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonRachStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteSonRachGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeTimeGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeTimeStatusGetResult nodeTimeGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeTimeGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeTimeStatusGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#iRelayStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.IRelayStatusGetResult iRelayStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iRelayStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.IRelayStatusGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#iBridgeTermRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.IBridgeTermRfGetResult iBridgeTermRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.IBridgeTermRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbSonRsiStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteSonRsiGetResult enbSonRsiStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonRsiStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteSonRsiGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#enbRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.LteRfGetResult enbRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.LteRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#ib440CommissionedPropertiesGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.Ib440CommissionedPropertiesGetResult ib440CommissionedPropertiesGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440CommissionedPropertiesGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.Ib440CommissionedPropertiesGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodePowerGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeSensorGetResult nodePowerGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodePowerGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#ib440RfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.Ib440RfGetResult ib440RfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440RfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.Ib440RfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodeCurrentGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodeSensorGetResult nodeCurrentGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeCurrentGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#iRelayScanListGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.IRelayScanListGetResult iRelayScanListGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iRelayScanListGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.IRelayScanListGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_14_50.API.Status.StatusSoap#nodePtpGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_14_50.API.Status.Credentials  credentials )*
     */
    public Netspan.NBI_14_50.API.Status.NodePtpGetResult nodePtpGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodePtpGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_14_50.API.Status.NodePtpGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }


}
