
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package Netspan.NBI_15_1.Status;
import java.util.logging.Logger;
/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-12-06T19:17:53.883+02:00
 * Generated source version: 3.0.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "Status",
                      portName = "StatusSoap",
                      targetNamespace = "http://Airspan.Netspan.WebServices",
                      wsdlLocation = "http://192.168.58.103//ws/15.0/Status.asmx?WSDL",
                      endpointInterface = "Netspan.NBI_15_1.Status.StatusSoap")
                      
public class StatusSoapImpl implements StatusSoap {

    private static final Logger LOG = Logger.getLogger(StatusSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbNetworkElementStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteNetworkElementGetResult enbNetworkElementStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbNetworkElementStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteNetworkElementGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeCurrentGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeSensorGetResult nodeCurrentGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeCurrentGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbCSonStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteSonMcimGetResult enbCSonStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbCSonStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteSonMcimGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#relayCdclListGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.RelayCdclListGetResult relayCdclListGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation relayCdclListGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.RelayCdclListGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#ib440RfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.Ib440RfGetResult ib440RfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440RfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.Ib440RfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#ib440InterfaceStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.Ib440InterfaceGetResult ib440InterfaceStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440InterfaceStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.Ib440InterfaceGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeTimeGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeTimeStatusGetResult nodeTimeGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeTimeGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeTimeStatusGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#ib440CommissionedPropertiesGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.Ib440CommissionedPropertiesGetResult ib440CommissionedPropertiesGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation ib440CommissionedPropertiesGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.Ib440CommissionedPropertiesGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbSonAnrStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteSonAnrGetResult enbSonAnrStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonAnrStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteSonAnrGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodePtpGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodePtpGetResult nodePtpGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodePtpGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodePtpGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#iBridgeTermRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.IBridgeTermRfGetResult iBridgeTermRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iBridgeTermRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.IBridgeTermRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbIpThroughputStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteIpThroughputGetResult enbIpThroughputStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbIpThroughputStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteIpThroughputGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbSonPciStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteSonPciGetResult enbSonPciStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonPciStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteSonPciGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbCachedCellStatusGet(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteCellStatusCachedListResult enbCachedCellStatusGet(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation enbCachedCellStatusGet");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteCellStatusCachedListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeSoftwareStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeSoftwareGetResult nodeSoftwareStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeSoftwareStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeSoftwareGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbEmbmsStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeEmbmsGetResult enbEmbmsStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbEmbmsStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeEmbmsGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#relayScanListGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.RelayScanListGetResult relayScanListGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation relayScanListGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.RelayScanListGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeGpsGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeGpsGetResult nodeGpsGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeGpsGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeGpsGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteRfGetResult enbRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodePowerGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeSensorGetResult nodePowerGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodePowerGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeVoltageGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeSensorGetResult nodeVoltageGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeVoltageGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbBackhaulInterfaceStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteBackhaulIfGetResult enbBackhaulInterfaceStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbBackhaulInterfaceStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteBackhaulIfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbWifiStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteWifiGetResult enbWifiStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbWifiStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteWifiGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbConnectedUeStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteUeGetResult enbConnectedUeStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbConnectedUeStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteUeGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbCachedAnrStatusGet(java.util.List<java.lang.String>  nodeName ,)java.util.List<java.lang.String>  nodeId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteCachedAnrListResult enbCachedAnrStatusGet(java.util.List<java.lang.String> nodeName,java.util.List<java.lang.String> nodeId,Credentials credentials) { 
        LOG.info("Executing operation enbCachedAnrStatusGet");
        System.out.println(nodeName);
        System.out.println(nodeId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteCachedAnrListResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbSonRsiStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteSonRsiGetResult enbSonRsiStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonRsiStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteSonRsiGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#nodeTemperatureGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.NodeSensorGetResult nodeTemperatureGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation nodeTemperatureGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.NodeSensorGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#iBridgeBaseRfStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.IBridgeBaseRfGetResult iBridgeBaseRfStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation iBridgeBaseRfStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.IBridgeBaseRfGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#relayStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.RelayStatusGetResult relayStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation relayStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.RelayStatusGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see Netspan.NBI_15_1.Status.StatusSoap#enbSonRachStatusGet(java.lang.String  nodeNameOrId ,)Netspan.NBI_15_1.Status.Credentials  credentials )*
     */
    public Netspan.NBI_15_1.Status.LteSonRachGetResult enbSonRachStatusGet(java.lang.String nodeNameOrId,Credentials credentials) { 
        LOG.info("Executing operation enbSonRachStatusGet");
        System.out.println(nodeNameOrId);
        System.out.println(credentials);
        try {
            Netspan.NBI_15_1.Status.LteSonRachGetResult _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
