package Netspan.NBI_14_50.API.Backhaul;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-02T16:21:26.175+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://Airspan.Netspan.WebServices", name = "BackhaulSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface BackhaulSoap {

    /**
     * Create a Pnp Config on NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigCreate")
    @WebMethod(operationName = "IBridgeBasePnpConfigCreate", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigCreate")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBasePnpConfigCreate(
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeBaseDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbBaseDetails iBridgeBaseDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iRelay Profiles.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileList")
    @WebMethod(operationName = "IRelayProfileList", action = "http://Airspan.Netspan.WebServices/IRelayProfileList")
    @ResponseWrapper(localName = "IRelayProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iRelayProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Deletes one or more of the iBridge Base management profiles in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileDelete")
    @WebMethod(operationName = "IBridgeBaseManagementProfileDelete", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileDelete")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseManagementProfileDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigClone")
    @WebMethod(operationName = "IBridgeTermPnpConfigClone", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigClone")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeTermPnpConfigClone(
        @WebParam(name = "ExistingNodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String existingNodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeTermDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermDetails iBridgeTermDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Produces a list of names of iBridge Base System Default Profiles configured in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseSystemDefaultProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseSystemDefaultProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseSystemDefaultProfileList")
    @WebMethod(operationName = "IBridgeBaseSystemDefaultProfileList", action = "http://Airspan.Netspan.WebServices/IBridgeBaseSystemDefaultProfileList")
    @ResponseWrapper(localName = "IBridgeBaseSystemDefaultProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseSystemDefaultProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iBridgeBaseSystemDefaultProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a iBridge Term Radio Profile on the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileCreate")
    @WebMethod(operationName = "IBridgeTermRadioProfileCreate", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileCreate")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeTermRadioProfileCreate(
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbTermRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a iBridge Base Management Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileGet")
    @WebMethod(operationName = "IBridgeBaseManagementProfileGet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileGet")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbBaseManagementProfileGetResult iBridgeBaseManagementProfileGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iRelay Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigList")
    @WebMethod(operationName = "IRelayPnpConfigList", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigList")
    @ResponseWrapper(localName = "IRelayPnpConfigListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeListResult iRelayPnpConfigList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the iBridge Term configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermConfigGet")
    @WebMethod(operationName = "IBridgeTermConfigGet", action = "http://Airspan.Netspan.WebServices/IBridgeTermConfigGet")
    @ResponseWrapper(localName = "IBridgeTermConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbTermConfigGetResult iBridgeTermConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a iRelay Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileGet")
    @WebMethod(operationName = "IRelayProfileGet", action = "http://Airspan.Netspan.WebServices/IRelayProfileGet")
    @ResponseWrapper(localName = "IRelayProfileGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IRelayProfileGetResult iRelayProfileGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the iRelay configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayConfigGet")
    @WebMethod(operationName = "IRelayConfigGet", action = "http://Airspan.Netspan.WebServices/IRelayConfigGet")
    @ResponseWrapper(localName = "IRelayConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IRelayConfigGetResult iRelayConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a iRelay Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileClone")
    @WebMethod(operationName = "IRelayProfileClone", action = "http://Airspan.Netspan.WebServices/IRelayProfileClone")
    @ResponseWrapper(localName = "IRelayProfileCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iRelayProfileClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "IRelayProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayProfile iRelayProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more iRelay Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigDelete")
    @WebMethod(operationName = "IRelayPnpConfigDelete", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigDelete")
    @ResponseWrapper(localName = "IRelayPnpConfigDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iRelayPnpConfigDelete(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a iBridge Base Management Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileClone")
    @WebMethod(operationName = "IBridgeBaseManagementProfileClone", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileClone")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseManagementProfileClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "ManagementProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfile managementProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Deletes one or more of the iBridge Term Radio profiles in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileDelete")
    @WebMethod(operationName = "IBridgeTermRadioProfileDelete", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileDelete")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeTermRadioProfileDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Ib440 configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "Ib440ConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "Ib440ConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.Ib440ConfigGet")
    @WebMethod(operationName = "Ib440ConfigGet", action = "http://Airspan.Netspan.WebServices/Ib440ConfigGet")
    @ResponseWrapper(localName = "Ib440ConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.Ib440ConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.Ib440ConfigGetResult ib440ConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a iBridge Base Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileClone")
    @WebMethod(operationName = "IBridgeBaseRadioProfileClone", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileClone")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseRadioProfileClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigUpdate")
    @WebMethod(operationName = "IBridgeTermPnpConfigUpdate", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigUpdate")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeTermPnpConfigUpdate(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeTermDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermDetails iBridgeTermDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the iBridge Base State for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseStateGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseStateGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseStateGet")
    @WebMethod(operationName = "IBridgeBaseStateGet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseStateGet")
    @ResponseWrapper(localName = "IBridgeBaseStateGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseStateGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbBaseStateGetResult iBridgeBaseStateGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the iBridge Base configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseConfigGet")
    @WebMethod(operationName = "IBridgeBaseConfigGet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseConfigGet")
    @ResponseWrapper(localName = "IBridgeBaseConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbBaseConfigGetResult iBridgeBaseConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a iBridge Base Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileUpdate")
    @WebMethod(operationName = "IBridgeBaseRadioProfileUpdate", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileUpdate")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseRadioProfileUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the iBridge Base configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseConfigSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseConfigSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseConfigSet")
    @WebMethod(operationName = "IBridgeBaseConfigSet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseConfigSet")
    @ResponseWrapper(localName = "IBridgeBaseConfigSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseConfigSetResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBaseConfigSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "IBridgeBaseDetails", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbBaseDetails iBridgeBaseDetails,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the parameters of a PNP IBridgeTerm configuration for the specified node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigGet")
    @WebMethod(operationName = "IBridgeTermPnpConfigGet", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigGet")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigGetResult iBridgeTermPnpConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a Pnp Config on NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigCreate")
    @WebMethod(operationName = "IBridgeTermPnpConfigCreate", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigCreate")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeTermPnpConfigCreate(
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeTermDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermDetails iBridgeTermDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iBridge Base Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigList")
    @WebMethod(operationName = "IBridgeBasePnpConfigList", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigList")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeListResult iBridgeBasePnpConfigList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a iBridge Base Management Profile on the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileCreate")
    @WebMethod(operationName = "IBridgeBaseManagementProfileCreate", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileCreate")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseManagementProfileCreate(
        @WebParam(name = "ManagementProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfile managementProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a iBridge Base Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileGet")
    @WebMethod(operationName = "IBridgeBaseRadioProfileGet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileGet")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbBaseRadioProfileGetResult iBridgeBaseRadioProfileGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more IBridgeBase Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigDelete")
    @WebMethod(operationName = "IBridgeBasePnpConfigDelete", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigDelete")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBasePnpConfigDelete(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigUpdate")
    @WebMethod(operationName = "IBridgeBasePnpConfigUpdate", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigUpdate")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBasePnpConfigUpdate(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeBaseDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbBaseDetails iBridgeBaseDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the parameters of a PNP iRelay configuration for the specified node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigGet")
    @WebMethod(operationName = "IRelayPnpConfigGet", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigGet")
    @ResponseWrapper(localName = "IRelayPnpConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigGetResult iRelayPnpConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the iRelay configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayConfigSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayConfigSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayConfigSet")
    @WebMethod(operationName = "IRelayConfigSet", action = "http://Airspan.Netspan.WebServices/IRelayConfigSet")
    @ResponseWrapper(localName = "IRelayConfigSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayConfigSetResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iRelayConfigSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "IRelayDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayDetails iRelayDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the iBridge Term configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermConfigSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermConfigSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermConfigSet")
    @WebMethod(operationName = "IBridgeTermConfigSet", action = "http://Airspan.Netspan.WebServices/IBridgeTermConfigSet")
    @ResponseWrapper(localName = "IBridgeTermConfigSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermConfigSetResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeTermConfigSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "IBridgeTermDetails", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeTermDetails iBridgeTermDetails,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more IBridgeTerm Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigDelete")
    @WebMethod(operationName = "IBridgeTermPnpConfigDelete", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigDelete")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeTermPnpConfigDelete(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Produces a list of names of iRelay System Default Profiles configured in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelaySystemDefaultProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelaySystemDefaultProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelaySystemDefaultProfileList")
    @WebMethod(operationName = "IRelaySystemDefaultProfileList", action = "http://Airspan.Netspan.WebServices/IRelaySystemDefaultProfileList")
    @ResponseWrapper(localName = "IRelaySystemDefaultProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelaySystemDefaultProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iRelaySystemDefaultProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigUpdate")
    @WebMethod(operationName = "IRelayPnpConfigUpdate", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigUpdate")
    @ResponseWrapper(localName = "IRelayPnpConfigUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iRelayPnpConfigUpdate(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayPnpDetailWs pnpDetail,
        @WebParam(name = "IRelayDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayDetails iRelayDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iBridge Base Radio Profiles.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileList")
    @WebMethod(operationName = "IBridgeBaseRadioProfileList", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileList")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iBridgeBaseRadioProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Deletes one or more of the iBridge Base Radio profiles in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileDelete")
    @WebMethod(operationName = "IBridgeBaseRadioProfileDelete", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileDelete")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseRadioProfileDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iBridge Term Plug and play configurations.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermPnpConfigListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermPnpConfigList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigList")
    @WebMethod(operationName = "IBridgeTermPnpConfigList", action = "http://Airspan.Netspan.WebServices/IBridgeTermPnpConfigList")
    @ResponseWrapper(localName = "IBridgeTermPnpConfigListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermPnpConfigListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeListResult iBridgeTermPnpConfigList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a Pnp Config on NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigCreate")
    @WebMethod(operationName = "IRelayPnpConfigCreate", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigCreate")
    @ResponseWrapper(localName = "IRelayPnpConfigCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iRelayPnpConfigCreate(
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayPnpDetailWs pnpDetail,
        @WebParam(name = "IRelayDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayDetails iRelayDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a iRelay Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileUpdate")
    @WebMethod(operationName = "IRelayProfileUpdate", action = "http://Airspan.Netspan.WebServices/IRelayProfileUpdate")
    @ResponseWrapper(localName = "IRelayProfileUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iRelayProfileUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "IRelayProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayProfile iRelayProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigClone")
    @WebMethod(operationName = "IBridgeBasePnpConfigClone", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigClone")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBasePnpConfigClone(
        @WebParam(name = "ExistingNodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String existingNodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpDetailWs pnpDetail,
        @WebParam(name = "iBridgeBaseDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbBaseDetails iBridgeBaseDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the iBridge Base State for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseStateSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseStateSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseStateSet")
    @WebMethod(operationName = "IBridgeBaseStateSet", action = "http://Airspan.Netspan.WebServices/IBridgeBaseStateSet")
    @ResponseWrapper(localName = "IBridgeBaseStateSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseStateSetResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iBridgeBaseStateSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "IBridgeBaseRfState", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbBaseStates iBridgeBaseRfState,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Produces a list of names of iBridge Term System Default Profiles configured in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermSystemDefaultProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermSystemDefaultProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermSystemDefaultProfileList")
    @WebMethod(operationName = "IBridgeTermSystemDefaultProfileList", action = "http://Airspan.Netspan.WebServices/IBridgeTermSystemDefaultProfileList")
    @ResponseWrapper(localName = "IBridgeTermSystemDefaultProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermSystemDefaultProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iBridgeTermSystemDefaultProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a iBridge Term Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileUpdate")
    @WebMethod(operationName = "IBridgeTermRadioProfileUpdate", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileUpdate")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeTermRadioProfileUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbTermRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a iBridge Base Management Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileUpdate")
    @WebMethod(operationName = "IBridgeBaseManagementProfileUpdate", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileUpdate")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileUpdateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseManagementProfileUpdate(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String name,
        @WebParam(name = "ManagementProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfile managementProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iBridge Base Management Profiles.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseManagementProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseManagementProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileList")
    @WebMethod(operationName = "IBridgeBaseManagementProfileList", action = "http://Airspan.Netspan.WebServices/IBridgeBaseManagementProfileList")
    @ResponseWrapper(localName = "IBridgeBaseManagementProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseManagementProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iBridgeBaseManagementProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of iBridge Term Radio Profiles.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileList")
    @WebMethod(operationName = "IBridgeTermRadioProfileList", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileList")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileListResponse")
    public Netspan.NBI_14_50.API.Backhaul.NameResult iBridgeTermRadioProfileList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Set the Ib440 configuration for the specified Node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "Ib440ConfigSetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "Ib440ConfigSet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.Ib440ConfigSet")
    @WebMethod(operationName = "Ib440ConfigSet", action = "http://Airspan.Netspan.WebServices/Ib440ConfigSet")
    @ResponseWrapper(localName = "Ib440ConfigSetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.Ib440ConfigSetResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult ib440ConfigSet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeName,
        @WebParam(name = "Ib440Details", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.Ib440DetailsSetWs ib440Details,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a iBridge Term Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileClone")
    @WebMethod(operationName = "IBridgeTermRadioProfileClone", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileClone")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeTermRadioProfileClone(
        @WebParam(name = "CloneFromName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String cloneFromName,
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IbTermRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a iBridge Base Radio Profile on the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBaseRadioProfileCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBaseRadioProfileCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileCreate")
    @WebMethod(operationName = "IBridgeBaseRadioProfileCreate", action = "http://Airspan.Netspan.WebServices/IBridgeBaseRadioProfileCreate")
    @ResponseWrapper(localName = "IBridgeBaseRadioProfileCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfileCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iBridgeBaseRadioProfileCreate(
        @WebParam(name = "RadioProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IBridgeBaseRadioProfile radioProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a iBridge Term Radio Profile from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeTermRadioProfileGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeTermRadioProfileGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileGet")
    @WebMethod(operationName = "IBridgeTermRadioProfileGet", action = "http://Airspan.Netspan.WebServices/IBridgeTermRadioProfileGet")
    @ResponseWrapper(localName = "IBridgeTermRadioProfileGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeTermRadioProfileGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IbTermRadioProfileGetResult iBridgeTermRadioProfileGet(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the parameters of a PNP IBridgeBase configuration for the specified node in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IBridgeBasePnpConfigGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IBridgeBasePnpConfigGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigGet")
    @WebMethod(operationName = "IBridgeBasePnpConfigGet", action = "http://Airspan.Netspan.WebServices/IBridgeBasePnpConfigGet")
    @ResponseWrapper(localName = "IBridgeBasePnpConfigGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigGetResponse")
    public Netspan.NBI_14_50.API.Backhaul.IBridgeBasePnpConfigGetResult iBridgeBasePnpConfigGet(
        @WebParam(name = "NodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeName,
        @WebParam(name = "NodeId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> nodeId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Deletes one or more of the iRelay profiles in the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileDelete")
    @WebMethod(operationName = "IRelayProfileDelete", action = "http://Airspan.Netspan.WebServices/IRelayProfileDelete")
    @ResponseWrapper(localName = "IRelayProfileDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileDeleteResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iRelayProfileDelete(
        @WebParam(name = "Name", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> name,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a iRelay Profile on the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayProfileCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayProfileCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileCreate")
    @WebMethod(operationName = "IRelayProfileCreate", action = "http://Airspan.Netspan.WebServices/IRelayProfileCreate")
    @ResponseWrapper(localName = "IRelayProfileCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayProfileCreateResponse")
    public Netspan.NBI_14_50.API.Backhaul.ProfileResponse iRelayProfileCreate(
        @WebParam(name = "IRelayProfile", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayProfile iRelayProfile,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Clone a Pnp Config from NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "IRelayPnpConfigCloneResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "IRelayPnpConfigClone", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigClone")
    @WebMethod(operationName = "IRelayPnpConfigClone", action = "http://Airspan.Netspan.WebServices/IRelayPnpConfigClone")
    @ResponseWrapper(localName = "IRelayPnpConfigCloneResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Backhaul.IRelayPnpConfigCloneResponse")
    public Netspan.NBI_14_50.API.Backhaul.NodeActionResult iRelayPnpConfigClone(
        @WebParam(name = "ExistingNodeName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String existingNodeName,
        @WebParam(name = "PnpDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayPnpDetailWs pnpDetail,
        @WebParam(name = "IRelayDetail", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Backhaul.IRelayDetails iRelayDetail,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );
}
