package Netspan.NBI_17_0.Software;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2019-03-05T12:46:48.576+02:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "Software",
                  wsdlLocation = "http://192.168.58.103/ws/17.0/Software.asmx?WSDL",
                  targetNamespace = "http://Airspan.Netspan.WebServices")
public class Software extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Airspan.Netspan.WebServices", "Software");
    public final static QName SoftwareSoap = new QName("http://Airspan.Netspan.WebServices", "SoftwareSoap");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.58.103/ws/17.0/Software.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Software.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://192.168.58.103/ws/17.0/Software.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public Software(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Software(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Software() {
        super(WSDL_LOCATION, SERVICE);
    }

    public Software(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Software(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Software(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns SoftwareSoap
     */
    @WebEndpoint(name = "SoftwareSoap")
    public SoftwareSoap getSoftwareSoap() {
        return super.getPort(SoftwareSoap, SoftwareSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoftwareSoap
     */
    @WebEndpoint(name = "SoftwareSoap")
    public SoftwareSoap getSoftwareSoap(WebServiceFeature... features) {
        return super.getPort(SoftwareSoap, SoftwareSoap.class, features);
    }

}
