package Netspan.NBI_14_50.API.Server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2016-03-02T16:25:01.591+02:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://Airspan.Netspan.WebServices", name = "ServerSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ServerSoap {

    /**
     * Returns NMS info.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsInfoGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsInfoGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsInfoGet")
    @WebMethod(operationName = "NmsInfoGet", action = "http://Airspan.Netspan.WebServices/NmsInfoGet")
    @ResponseWrapper(localName = "NmsInfoGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsInfoGetResponse")
    public Netspan.NBI_14_50.API.Server.NmsInfoResponse nmsInfoGet(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get a NMS User from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsUserGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsUserGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserGet")
    @WebMethod(operationName = "NmsUserGet", action = "http://Airspan.Netspan.WebServices/NmsUserGet")
    @ResponseWrapper(localName = "NmsUserGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserGetResponse")
    public Netspan.NBI_14_50.API.Server.NmsUserGetResult nmsUserGet(
        @WebParam(name = "UserName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> userName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Returns a list of NMS Users.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsUserListResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsUserList", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserList")
    @WebMethod(operationName = "NmsUserList", action = "http://Airspan.Netspan.WebServices/NmsUserList")
    @ResponseWrapper(localName = "NmsUserListResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserListResponse")
    public Netspan.NBI_14_50.API.Server.NameResult nmsUserList(
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Create a NMS User on the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsUserCreateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsUserCreate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserCreate")
    @WebMethod(operationName = "NmsUserCreate", action = "http://Airspan.Netspan.WebServices/NmsUserCreate")
    @ResponseWrapper(localName = "NmsUserCreateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserCreateResponse")
    public Netspan.NBI_14_50.API.Server.UserResponse nmsUserCreate(
        @WebParam(name = "NmsUser", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Server.NmsUserSetWs nmsUser,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Update a NMS User from the NMS. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsUserUpdateResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsUserUpdate", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserUpdate")
    @WebMethod(operationName = "NmsUserUpdate", action = "http://Airspan.Netspan.WebServices/NmsUserUpdate")
    @ResponseWrapper(localName = "NmsUserUpdateResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserUpdateResponse")
    public Netspan.NBI_14_50.API.Server.UserResponse nmsUserUpdate(
        @WebParam(name = "UserName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String userName,
        @WebParam(name = "NmsUser", targetNamespace = "http://Airspan.Netspan.WebServices")
        Netspan.NBI_14_50.API.Server.NmsUserSetWs nmsUser,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Delete one or more NMS Users.  Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NmsUserDeleteResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NmsUserDelete", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserDelete")
    @WebMethod(operationName = "NmsUserDelete", action = "http://Airspan.Netspan.WebServices/NmsUserDelete")
    @ResponseWrapper(localName = "NmsUserDeleteResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_50.API.Server.NmsUserDeleteResponse")
    public Netspan.NBI_14_50.API.Server.UserResponse nmsUserDelete(
        @WebParam(name = "UserName", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.util.List<java.lang.String> userName,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );
}
