package Netspan.NBI_14_0.API.Status;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.1
 * 2015-07-05T12:19:30.840+03:00
 * Generated source version: 3.0.1
 * 
 */
@WebService(targetNamespace = "http://Airspan.Netspan.WebServices", name = "StatusSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface StatusSoap {

    /**
     * Get the current GPS status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeGpsGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeGpsGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeGpsGet")
    @WebMethod(operationName = "NodeGpsGet", action = "http://Airspan.Netspan.WebServices/NodeGpsGet")
    @ResponseWrapper(localName = "NodeGpsGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeGpsGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeGpsGetResult nodeGpsGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Backhaul Interface status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbBackhaulInterfaceStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbBackhaulInterfaceStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbBackhaulInterfaceStatusGet")
    @WebMethod(operationName = "EnbBackhaulInterfaceStatusGet", action = "http://Airspan.Netspan.WebServices/EnbBackhaulInterfaceStatusGet")
    @ResponseWrapper(localName = "EnbBackhaulInterfaceStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbBackhaulInterfaceStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteBackhaulIfGetResult enbBackhaulInterfaceStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Current software status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeSoftwareStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeSoftwareStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeSoftwareStatusGet")
    @WebMethod(operationName = "NodeSoftwareStatusGet", action = "http://Airspan.Netspan.WebServices/NodeSoftwareStatusGet")
    @ResponseWrapper(localName = "NodeSoftwareStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeSoftwareStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeSoftwareGetResult nodeSoftwareStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the temperature sensor's status of the specified Node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeTemperatureGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeTemperatureGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeTemperatureGet")
    @WebMethod(operationName = "NodeTemperatureGet", action = "http://Airspan.Netspan.WebServices/NodeTemperatureGet")
    @ResponseWrapper(localName = "NodeTemperatureGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeTemperatureGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeSensorGetResult nodeTemperatureGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Son Auto Pci status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbSonPciStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbSonPciStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonPciStatusGet")
    @WebMethod(operationName = "EnbSonPciStatusGet", action = "http://Airspan.Netspan.WebServices/EnbSonPciStatusGet")
    @ResponseWrapper(localName = "EnbSonPciStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonPciStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteSonPciGetResult enbSonPciStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the voltage sensor's status of the specified Node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeVoltageGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeVoltageGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeVoltageGet")
    @WebMethod(operationName = "NodeVoltageGet", action = "http://Airspan.Netspan.WebServices/NodeVoltageGet")
    @ResponseWrapper(localName = "NodeVoltageGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeVoltageGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeSensorGetResult nodeVoltageGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the IP Throughput status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbIpThroughputStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbIpThroughputStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbIpThroughputStatusGet")
    @WebMethod(operationName = "EnbIpThroughputStatusGet", action = "http://Airspan.Netspan.WebServices/EnbIpThroughputStatusGet")
    @ResponseWrapper(localName = "EnbIpThroughputStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbIpThroughputStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteIpThroughputGetResult enbIpThroughputStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the UE status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbConnectedUeStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbConnectedUeStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbConnectedUeStatusGet")
    @WebMethod(operationName = "EnbConnectedUeStatusGet", action = "http://Airspan.Netspan.WebServices/EnbConnectedUeStatusGet")
    @ResponseWrapper(localName = "EnbConnectedUeStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbConnectedUeStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteUeGetResult enbConnectedUeStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Son ANR status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbSonAnrStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbSonAnrStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonAnrStatusGet")
    @WebMethod(operationName = "EnbSonAnrStatusGet", action = "http://Airspan.Netspan.WebServices/EnbSonAnrStatusGet")
    @ResponseWrapper(localName = "EnbSonAnrStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonAnrStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteSonAnrGetResult enbSonAnrStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Interface status. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "Ib440InterfaceStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "Ib440InterfaceStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440InterfaceStatusGet")
    @WebMethod(operationName = "Ib440InterfaceStatusGet", action = "http://Airspan.Netspan.WebServices/Ib440InterfaceStatusGet")
    @ResponseWrapper(localName = "Ib440InterfaceStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440InterfaceStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.Ib440InterfaceGetResult ib440InterfaceStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the time status of the specified Node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeTimeGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeTimeGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeTimeGet")
    @WebMethod(operationName = "NodeTimeGet", action = "http://Airspan.Netspan.WebServices/NodeTimeGet")
    @ResponseWrapper(localName = "NodeTimeGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeTimeGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeTimeStatusGetResult nodeTimeGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Son RSI status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbSonRsiStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbSonRsiStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonRsiStatusGet")
    @WebMethod(operationName = "EnbSonRsiStatusGet", action = "http://Airspan.Netspan.WebServices/EnbSonRsiStatusGet")
    @ResponseWrapper(localName = "EnbSonRsiStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbSonRsiStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteSonRsiGetResult enbSonRsiStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the RF status of the specified node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "EnbRfStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "EnbRfStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbRfStatusGet")
    @WebMethod(operationName = "EnbRfStatusGet", action = "http://Airspan.Netspan.WebServices/EnbRfStatusGet")
    @ResponseWrapper(localName = "EnbRfStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.EnbRfStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.LteRfGetResult enbRfStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the commissioned properties status. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "Ib440CommissionedPropertiesGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "Ib440CommissionedPropertiesGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440CommissionedPropertiesGet")
    @WebMethod(operationName = "Ib440CommissionedPropertiesGet", action = "http://Airspan.Netspan.WebServices/Ib440CommissionedPropertiesGet")
    @ResponseWrapper(localName = "Ib440CommissionedPropertiesGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440CommissionedPropertiesGetResponse")
    public Netspan.NBI_14_0.API.Status.Ib440CommissionedPropertiesGetResult ib440CommissionedPropertiesGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the power sensor's status of the specified Node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodePowerGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodePowerGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodePowerGet")
    @WebMethod(operationName = "NodePowerGet", action = "http://Airspan.Netspan.WebServices/NodePowerGet")
    @ResponseWrapper(localName = "NodePowerGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodePowerGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeSensorGetResult nodePowerGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the Rf status. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "Ib440RfStatusGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "Ib440RfStatusGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440RfStatusGet")
    @WebMethod(operationName = "Ib440RfStatusGet", action = "http://Airspan.Netspan.WebServices/Ib440RfStatusGet")
    @ResponseWrapper(localName = "Ib440RfStatusGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.Ib440RfStatusGetResponse")
    public Netspan.NBI_14_0.API.Status.Ib440RfGetResult ib440RfStatusGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );

    /**
     * Get the current sensor's status of the specified Node. Requires NBIF Extensions Licence.
     */
    @WebResult(name = "NodeCurrentGetResult", targetNamespace = "http://Airspan.Netspan.WebServices")
    @RequestWrapper(localName = "NodeCurrentGet", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeCurrentGet")
    @WebMethod(operationName = "NodeCurrentGet", action = "http://Airspan.Netspan.WebServices/NodeCurrentGet")
    @ResponseWrapper(localName = "NodeCurrentGetResponse", targetNamespace = "http://Airspan.Netspan.WebServices", className = "Netspan.NBI_14_0.API.Status.NodeCurrentGetResponse")
    public Netspan.NBI_14_0.API.Status.NodeSensorGetResult nodeCurrentGet(
        @WebParam(name = "NodeNameOrId", targetNamespace = "http://Airspan.Netspan.WebServices")
        java.lang.String nodeNameOrId,
        @WebParam(name = "Credentials", targetNamespace = "http://Airspan.Netspan.WebServices", header = true)
        Credentials credentials
    );
}
